---
title: "pre/post-sites"
output: html_document
---
```{r}
library(natverse)
library(tidyverse)
library(fafbseg)
library(RColorBrewer)
library(googlesheets4)
```


```{r}
# !!! hot to use!!
# either input type or single cell
#  types are taken from flywire neuron names sheet.
#  cell can be any valid flywire id

##type = "LC9"
 singlecell = "720575940629791275"  ## LC9, LC14a input

## LC9, LC14a input
##names <- read_sheet("14FS2ayAzV5gNq3sDQ6IuYfU_VrA3OltY-moant0EX-8")
##data <- data.frame(type = type, id = names$seg_id[names$type==type])
##data$id <- flywire_latestid(data$id)


# if using type: cell <- data$id
# if using single singlecell: cell <- singlecell 
# only run one of the following1

 cell <- singlecell 
# OR
##cell <- data$id





cell <- flywire_latestid(cell)


#  Output
#  plots one cell or all cells of a type (one cell per plot)
# output synapses are yellow, input synapses are red
```

```{r}


post <- flywire_partners(cell, details = TRUE, partners = c("outputs")) %>% filter(cleft_scores >= 100)
##post <- data.frame(post[,c(3,4,5,19,20)])
post <- data.frame(post[,c("post_x","post_y","post_z","post_id","pre_id")])
post$post_id <- as.character(post$post_id)
A <- post %>% group_by(pre_id) %>% add_count(post_id)
post <-A
post <- subset(post,post_id !=pre_id)


pre <- flywire_partners(cell, details = TRUE, partners = c("inputs")) %>% filter(cleft_scores >= 100)
##pre <- data.frame(pre[,c(3,4,5,19,20)])
pre <- data.frame(pre[,c("pre_x","pre_y","pre_z","post_id","pre_id")])
pre$pre_id <- as.character(pre$pre_id)
A <- pre %>%group_by(post_id) %>%  add_count(pre_id)
pre <-A
pre <- subset(pre,pre_id !=post_id)
```

```{r}
cells <- read_cloudvolume_meshes(cell)
```





```{r}
i=1

nopen3d()
par3d('windowRect' = c(100,100,2000,1100))
  
for (i in 1:length(cells)){

  shade3d(as.mesh3d(FAFB14NP.surf), alpha=0.05, col='gray', lit=T)
  plot3d(cells[i], col = "black", lit=F)
  spheres3d(post[ which(post$pre_id==unique(post$pre_id)[i]),1:3],col="yellow",radius = 900,lit=F)
  spheres3d(pre[ which(pre$post_id==unique(pre$post_id)[i]),1:3],col="red",radius = 900,lit=F)
  view3d(fov=0,zoom=0.5, userMatrix= rotationMatrix(0/180*pi,0,0,1) %*% rotationMatrix(180/180*pi,1,0,0))
  rgl.snapshot(filename= paste("try3/",cell[i],"red_yellow_front.png", sep=""))
  view3d(fov=0,zoom=0.5, userMatrix= rotationMatrix(0/180*pi,0,0,1) %*% rotationMatrix(-90/180*pi,1,0,0))
  rgl.snapshot(filename= paste("try3/",cell[i],"red_yellow_top.png", sep=""))
  clear3d()
  }

i=1

nopen3d()
par3d('windowRect' = c(100,100,2000,1100))
  
for (i in 1:length(cells)){
 
  shade3d(as.mesh3d(FAFB14NP.surf), alpha=0.05, col='gray', lit=T)
  plot3d(cells[i], col = "black", lit=F)
  spheres3d(post[ which(post$pre_id==unique(post$pre_id)[i]),1:3],col="yellow",radius = 900,lit=F)
  view3d(fov=0,zoom=0.5, userMatrix= rotationMatrix(0/180*pi,0,0,1) %*% rotationMatrix(180/180*pi,1,0,0))
  rgl.snapshot(filename= paste("try3/",cell[i],"yellow_front.png", sep=""))
  view3d(fov=0,zoom=0.5, userMatrix= rotationMatrix(0/180*pi,0,0,1) %*% rotationMatrix(-90/180*pi,1,0,0))
  rgl.snapshot(filename= paste("try3/",cell[i],"yellow_top.png", sep=""))
  clear3d()
  }

i=1

nopen3d()
par3d('windowRect' = c(100,100,2000,1100))
  
for (i in 1:length(cells)){

  shade3d(as.mesh3d(FAFB14NP.surf), alpha=0.05, col='gray', lit=T)
  plot3d(cells[i], col = "black", lit=F)
  spheres3d(pre[ which(pre$post_id==unique(pre$post_id)[i]),1:3],col="red",radius = 900,lit=F)
  view3d(fov=0,zoom=0.5, userMatrix= rotationMatrix(0/180*pi,0,0,1) %*% rotationMatrix(180/180*pi,1,0,0))
  rgl.snapshot(filename= paste("try3/",cell[i],"red_front.png", sep=""))
  view3d(fov=0,zoom=0.5, userMatrix= rotationMatrix(0/180*pi,0,0,1) %*% rotationMatrix(-90/180*pi,1,0,0))
  rgl.snapshot(filename= paste("try3/",cell[i],"red_top.png", sep=""))
  clear3d()
  }
```

